name: Auto Fetch TikTok Videos

on:
  schedule:
    - cron: '0 */6 * * *' # හැම පැය 6කට වරක්ම කිසිම මැදිහත් වීමක් නැතිව ක්‍රියාත්මක වේ
  workflow_dispatch: # ඔබට අවශ්‍ය නම් GitHub එකෙන් බටන් එක ඔබලා ඕනෑම වෙලාවක රන් කල හැක

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Fetch Script
      run: python fetch_videos.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'GitHub Action Bot'
        git config --global user.email 'action@github.com'
        git add videos.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Fresh videos updated" && git push)
